[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
two_sided_services_marketplace = "DRZPfcvLTK73RVEWyG3hqQ3BkDtbHeUDAn5Z6ScXHqF2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
